### ISSUE TITLE
Mapping Error

### ISSUE THREAD

**Issue by priyankark** [psauthor/WebApiFundamentals#5]
While following the instructions in the course, in the "adding the talks to api part", I am encountering the following error while calling the api:

```
{
    "message": "An error has occurred.",
    "exceptionMessage": "Error mapping types.\r\n\r\nMapping types:\r\nCamp[] -> IEnumerable`1\r\nTheCodeCamp.Data.Camp[] -> System.Collections.Generic.IEnumerable`1[[TheCodeCamp.Models.CampModel, TheCodeCamp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]",
    "exceptionType": "AutoMapper.AutoMapperMappingException",
    "stackTrace": "   at lambda_method(Closure , Camp[] , IEnumerable`1 , ResolutionContext )\r\n   at lambda_method(Closure , Object , Object , ResolutionContext )\r\n   at TheCodeCamp.Controllers.CampsController.<Get>d__3.MoveNext() in C:\\Users\\priykum\\Desktop\\WebApiFundamentals-master\\WebApiFundamentals-master\\starting\\TheCodeCamp\\Controllers\\CampsController.cs:line 36",
    "innerException": {
        "message": "An error has occurred.",
        "exceptionMessage": "Error mapping types.\r\n\r\nMapping types:\r\nCamp -> CampModel\r\nTheCodeCamp.Data.Camp -> TheCodeCamp.Models.CampModel\r\n\r\nType Map configuration:\r\nCamp -> CampModel\r\nTheCodeCamp.Data.Camp -> TheCodeCamp.Models.CampModel\r\n\r\nDestination Member:\r\nTalks\r\n",
        "exceptionType": "AutoMapper.AutoMapperMappingException",
        "stackTrace": "   at lambda_method(Closure , Camp[] , IEnumerable`1 , ResolutionContext )",
        "innerException": {
            "message": "An error has occurred.",
            "exceptionMessage": "Missing type map configuration or unsupported mapping.\r\n\r\nMapping types:\r\nTalk -> TalkModel\r\nTheCodeCamp.Data.Talk -> TheCodeCamp.Models.TalkModel",
            "exceptionType": "AutoMapper.AutoMapperMappingException",
            "stackTrace": "   at lambda_method(Closure , Talk , TalkModel , ResolutionContext )\r\n   at lambda_method(Closure , Camp[] , IEnumerable`1 , ResolutionContext )"
        }
    }
}
```

Can I get some assistance on this? 

Thank you and regards,
Priyankar

**Comment by BerkBorak** [comment]
As far as I remember I resolved this issue by creating and adding the code for AutoMapper to TalksMapper.

**Comment by shawnwildermuth** [comment]
Yes, add Talks and Speakers to the mapper. But please use the discussion tab in the course to ask questions. I can't answer them here.

**Comment by abdessamadjadid** [comment]
Thanks guys for saving my day , the solutions is just adding talks and Speaker to the mapper.

**Comment by PlasmaSoftUK** [comment]
I cannot believe this issue was found in 2019 and the PluralSight course has not been updated to reflect this. I just spent over an hour going though Session 3 that is only a 6 minute lesson, with a fine tooth comb trying to work out here I had gone wrong. Turns out I didn't go wrong!!! You need to add this to the CampMappingProfile.cs file ...

```
            CreateMap<Talk, TalkModel>();
            CreateMap<Speaker, SpeakerModel>();
```

**Comment by shawnwildermuth** [comment]
I am surprised too. I just updated the course and should have included this change. Let me check. Also, please contact me via the discussion tab on the course, I don't get to the issues in the repos very often.

**Comment by PlasmaSoftUK** [comment]
I've raised it on the discussion as well, but as this is where Google brought me I posted it here as well.

**Comment by ananthdashuri** [comment]
If your referring the Building an API with ASP.NET Core in Pluralsight, 
kindly check with the next video as shown below, In that you will get the clarity of this Automapper solution.

4. Modifying Data  -- Issue on PUT.
5. Creating Association APIs --Get clarity of the issue.

The exact issue is that when your mapping the Automapper with profiles you need to add the 
this.CreateMap<Camp, CampModel>().ReverseMap();

**.ReverseMap()** This makes sense.

**Comment by rahimlotfi1368** [comment]
I have the same problim

**Comment by shawnwildermuth** [comment]
Did you ask on the Discussion tab? I can't answer questions here.
